### ISSUE TITLE
Compare 2 XMLs with elements with attributes and un-ordered elements

### ISSUE THREAD

**Issue by JyothiAswathaiah** [xmlunit/xmlunit#109]
Hi,
We want the below 2 xmls to be marked as similar as they are just differing in their order. Tried various possibilites wiith XMLUnit 1 & 2 versions.

CONTROL:
```
<Fruits\>
<Apple size="13" color="green"/>
<Apple size="11" color="green"/>
</Fruits>
```
TEST:
```
<Fruits>
<Apple size="13" color="green"/>
<Apple size="11" color="green"/>
</Fruits>
```

Expected attribute value '11' but was '13' - comparing <Apple size="11" ...=""> at /Fruits[1]/Apple[1]/@size to <Apple size="13" ...=""> at /Fruits[1]/Apple[1]/@size
Expected attribute value '13' but was '11' - comparing <Apple size="13" ...=""> at /Fruits[1]/Apple[2]/@size to <Apple size="11" ...=""> at /Fruits[1]/Apple[2]/@size

Tried the below using XMLUnit2 with no luck ---
```
org.xmlunit.diff.Diff diff2 = DiffBuilder
	                .compare(SCXmlUtil.getString(expectedDocument))
	                .withTest(SCXmlUtil.getString(testDocument))
	                .ignoreComments()
	                .ignoreWhitespace()
	                .
	                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.and(
	                	    ElementSelectors.byNameAndText,
	                	    ElementSelectors.byNameAndAllAttributes)))	                
	                .build();
```

Any help on this will be greatly appreciated.

**Comment by bodewig** [comment]
I don't see any nested text in your example, so I'm not sure why you use `ElementSelectors.byNameAndText`.

What result do you see when you only use

```
.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndAllAttributes))
```

?

**Comment by JyothiAswathaiah** [comment]
Thanks a lot for the quick reply!! 
The actual XMLs are the following, they are only differing in the order of Service Element, else both Input and the TestXML are exactly the same:

**Input:**
\<ABC\>
	\<Service Name="getFruitList"\>
		\<Input\>
			\<Fruit Code="fruit1" GroupCode="T1" FruitID="FR123" UM="KG"\>
			\</Fruit\>
		\</Input\>
		\<Template\>
			\<FruitList\>
				\<Fruit GroupCode="" FruitID="" UM=""\>
					\<Ship SM="" TM=""\/>
				\</Fruit\>
			\</FruitList\>
		\</Template\>
	\</Service\>
		\<Service Name="getFruitList"\>
		\<Input\>
			\<Fruit Code="fruit1" GroupCode="T1" FruitID="FR234" UM="KG"\>
			\</Fruit\>
		\</Input\>
		\<Template\>
			\<FruitList\>
				\<Fruit GroupCode="" FruitID="" UM=""\>
					\<Ship SM="" TM=""\/>
				\</Fruit\>
			\</FruitList\>
		\</Template\>
	\</Service\>
\<Service Name="getFruitList"\>
		\<Input\>
			\<Fruit Code="fruit1" GroupCode="T1" FruitID="FR345" UM="KG"\>
			\</Fruit\>
		\</Input\>
		\<Template\>
			\<FruitList\>
				\<Fruit GroupCode="" FruitID="" UM=""\>
					\<Ship SM="" TM=""\/>
				\</Fruit\>
			\</FruitList\>
		\</Template\>
	\</Service\>
</ABC>

**TestXML:**
\<ABC\>
	\<Service Name="getFruitList"\>
		\<Input\>
			\<Fruit Code="fruit1" GroupCode="T1" FruitID="FR123" UM="KG"\>
			\</Fruit\>
		\</Input\>
		\<Template\>
			\<FruitList\>
				\<Fruit GroupCode="" FruitID="" UM=""\>
					\<Ship SM="" TM=""\/>
				\</Fruit\>
			\</FruitList\>
		\</Template\>
	\</Service\>
		\<Service Name="getFruitList"\>
		\<Input\>
			\<Fruit Code="fruit1" GroupCode="T1" FruitID="FR345" UM="KG"\>
			\</Fruit\>
		\</Input\>
		\<Template\>
			\<FruitList\>
				\<Fruit GroupCode="" FruitID="" UM=""\>
					\<Ship SM="" TM=""\/>
				\</Fruit\>
			\</FruitList\>
		\</Template\>
	\</Service\>
\<Service Name="getFruitList"\>
		\<Input\>
			\<Fruit Code="fruit1" GroupCode="T1" FruitID="FR234" UM="KG"\>
			\</Fruit\>
		\</Input\>
		\<Template\>
			\<FruitList\>
				\<Fruit GroupCode="" FruitID="" UM=""\>
					\<Ship SM="" TM=""\/>
				\</Fruit\>
			\</FruitList\>
		\</Template\>
	\</Service\>
</ABC>

Below is the output obtained using XML xmlunit-core-2.2.1.jar:
**Code Snippet:**
  org.xmlunit.diff.Diff diff2 = DiffBuilder
              .compare(input)
              .withTest(testXML)
              .ignoreComments()
              .ignoreWhitespace()
              .checkForSimilar()
              .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndAllAttributes)).build();
**Output:**
Expected child 'Fruit' but was 'null' - comparing <Fruit...> at /ABC[1]/Service[2]/Input[1]/Fruit[1] to <NULL>
4 Such messages 2 for I/p and 2 for TestXML

Below is the output obtained using XMLUnit 1.4jar
**Code snippet:**
 XMLUnit.setIgnoreAttributeOrder(true);
        XMLUnit.setIgnoreComments(true);
        XMLUnit.setIgnoreWhitespace(true);
        XMLUnit.setCompareUnmatched(false);

   org.custommonkey.xmlunit.Diff diff1 = new org.custommonkey.xmlunit.Diff(input,  testXML);
   diff1.overrideElementQualifier(new ElementNameAndAttributeQualifier());
**Output**
[different] Expected presence of child node 'Fruit' but was 'null' - comparing <Fruit...> at /ABC[1]/Service[2]/Input[1]/Fruit[1] to  at null

**using assertXMLEqual of 1.4 we get the message**
[different] Expected attribute value 'FR234' but was 'FR345' - comparing <Fruit FruitID="FR234"...> at /ABC[1]/SERVICE[2]/Input[1]/Fruit[1]/@FruitID to <Fruit FruitID="FR345"...> at /ABC[1]/SERVICE[2]/Input[1]/Fruit[1]/@FruitID

Thanks in Advance for all the help provided on this!

**Comment by bodewig** [comment]
I think you'll need to help me so I can help you. You are probably so deep into your domain that you think it is obvious what the expected result is, but it isn't to me.

At each level you when you look at sibling elements you need to ask yourself, what is it that identifies the elements, what is it that XMLUnit shall use in order to select the correct pair of elements to compare.

At the root element there is no choice, this is easy.

Next come the `Service` elements. What is it that identifies those that should be compared? All of them have the same name and the same value for their `Name` attribute. Are they all alike, i.e. can XMLUnit just pick any arbitrary combination of elements? Or is there anything that can be used to say pick the first one in control and the second one in test? It might be something like "Look at the `FruitID` attribute of the `Fruit` element nested into the `Input` child element of `Service`", but I'm guessing here.

You do so for all levels where sibling elements exist. Many times all siblings have different element names (like all children of `Service` seem to have unique names in your example) so figuring out how to pick the pairs is easy: use the element name and nothing else.

Once you have established what you need to identify the correct pairs you need to tell XMLUnit to use that approach. `ElementSelector` is what you need to tweak (I won't cover XMLUnit 1.x here). Often a single `ElementSelector` is good enough for all decisions inside of your document, then you just need to state that. But there are cases where it doesn't work and then you need a conditional selector.

If I'm guessing correctly then you'd need an `ElementSelectors.byName` for almost all decisions, but when it comes to the `Service` elements you need something that involves its grandchildren. The translation of my guess above is `ElementSeletors.byXpath("./Input/Fruit", ElementSelectors.byNameAndAttributes("FruitId"))` - i.e. pick the `Fruit` child of the `Input` child element and look at their `FruitId` attribute.

Then you'd combine all this with

```java
ElementSelectors.conditionalBuilder()
    .whenElementIsNames("Service")
    .thenUse(ElementSeletors.byXpath("./Input/Fruit", ElementSelectors.byNameAndAttributes("FruitId")))
    .elseUse(ElementSelectors.byName)
    .build()
```

If I'm guessing wrong you need to explain what really is telling the `Service` elements apart.

If this works for you it would be great if you could review https://github.com/xmlunit/user-guide/wiki/SelectingNodes and tell me what of my answer here is missing over there.

**Comment by JyothiAswathaiah** [comment]
Thanks a lot Stefan. This worked... I did look into the link shared by you even before I could post here, may be a simple example in the place of tr, th, td could make more clearer :)... Thanks Again

**Comment by bodewig** [comment]
Thanks. I'm glad it worked for you.
