### ISSUE TITLE
NodeFilter to ignore content

### ISSUE THREAD

**Issue by sebpiller** [xmlunit/xmlunit#127]
Hi,

thank you for this great library that really helps me to do lots of checks with my various xml generation tools. I'm actually needing to verify that the same node exist at the same path in 2 documents, but with no verification of the content. In fact, something very similar to DiffBuilder#withNodeFilter, but that still assert the node are here. Maybe DiffBuilder#withIgnorableContentNodeFilter?

For example:
a.xml
`<root><created>2018-01-01</created></root>`

b.xml
`<root><created>2018-01-12</created></root>`
... should match and 

a.xml
`<root><created>2018-01-01</created></root>`

b.xml
`<root><updated>2018-01-01</update></root>`
... should fail.

I've looked at the sources and the docs, but I'm actually not sure if this feature exists or not.

**Comment by bodewig** [comment]
I'd probably use a `DifferenceEnvaluator` rather than a `NodeFilter` for this as it feels more natural (there is a difference that you don't care about). `DifferenceEvaluators.downgradeDifferencesToEqual(ComparisonType.TEXT_VALUE)` would ignore all text differences, or you could write a `DifferenceEvaluator` of your own which would downgrade text node differences only if the parent node is an element named "created" - depends on whether you want to compare texts in other parts of your document or not.

You could achieve the same with a `NodeFilter` that dropped all `Text` nodes or just the text nodes that are children of an element named "created". There is no builtin `NodeFilter` that would do that, but writing a custom implementation of the interface should be straight forward.

**Comment by sebpiller** [comment]
Sorry for the delay. 

Indeed, an implementation like that does great job:

``
