### ISSUE TITLE
Improve org.xmlunit.builder.Input type safety

### ISSUE THREAD

**Issue by shapiy** [xmlunit/xmlunit#17]
Hi, 

Do you think it makes sense to replace the conditionals in `Input.from()` with overloaded methods? 

```java
Builder from(Source source);

Builder from(Builder builder);

// etc.
```

This way, `Input.fromX()` methods can be eliminated and we don’t emulate polymorphism with conditional branches.

**Comment by shapiy** [comment]
Perhaps, I should have started the discussion under the mailing list. Although, it’s not that suitable for code listings.

**Comment by bodewig** [comment]
:-)

The `from` method has been introduced at a later stage in order to implement `DiffBuilder` and @brabenetz' `CompareMatcher` more easily.  With overloads `DiffBuilder` will need the exact same overloads for `compare` and `withTest` as well.

If you look through the list archive you'll see I've been uneasy with `from` as well, but the expolsion of overloads isn't really more attractive to me.

**Comment by bodewig** [comment]
we'll stick with the ugly `if instanceof` cascade in order to simplify higher level APIs like `DiffBuilder` and `ComparisonMatcher`.
