### ISSUE TITLE
Unable to prove mismatch in attributs order with XMLUnit 1.6

### ISSUE THREAD

**Issue by abirbha** [xmlunit/xmlunit#170]
`public List<String> compare(@Argument("fichier XML source") String source, @Argument("fichier XML cible") String target) throws SAXException, IOException {

		List<String> totalDiff = new ArrayList<>();
		File sourceFile = new File(source);
		File targetFile = new File(target);
		// verification of files
		if ((sourceFile.isFile() && sourceFile.canRead()) && (targetFile.isFile() && targetFile.canRead())) {
			// Open the streams.
			FileInputStream fis1 = new FileInputStream(source);
			FileInputStream fis2 = new FileInputStream(target);
			try {
				// using BufferedReader for improved performance
				BufferedReader src = new BufferedReader(new InputStreamReader(fis1));
				BufferedReader tgt = new BufferedReader(new InputStreamReader(fis2));
				// configuring XMLUnit to ignore whitespaces
				// PS: if we don't configure this parameter any existance of
				// whitespaces would generate errors
				XMLUnit.setIgnoreWhitespace(true);
				// Attribute Order would generate errors
				XMLUnit.setIgnoreAttributeOrder(false);
				// creating Diff instance to compare two XML files
				Diff xmlDiff = new Diff(src, tgt);
				// for getting detailed differences between two xml files
				DetailedDiff detailXmlDiff = new DetailedDiff(xmlDiff);
				List<Difference> differences = detailXmlDiff.getAllDifferences();

				for (Difference difference : differences) {
					totalDiff.add(difference.toString());
				}

			} catch (Exception e) {
				fis1.close();
				fis2.close();
				BasicConfigurator.configure();
				logger.error(e.getMessage());
				BasicConfigurator.resetConfiguration();
				Assert.assertTrue(e.getMessage(), false);
			}
		}
		return totalDiff;
	}`

 **The 2 files to be compared are considered to be IDENTICAL.**
 example :
Balise : documents T="1"  D="1" V="7"  **is identical to**  Balise : documents D="1" T="1"  V="7"

**Comment by bodewig** [comment]
Attribute order is not significant in XML documents and the order of attributes you get from your XML parser may even depend on the parser implementation and version. Therefore XMLUnit doesn't even look at the order of attributes, this is a conscious design decision.

**Comment by bodewig** [comment]
Oops, sorry, I just now saw this is an issue for XMLUnit 1.6.

What I say above still is true, it may just be that the XML parser reorders attributes before providing them to XMLUnit 1.x so we don't even see the difference in the order of attributes. 

I believe you are trying to test something that you shouldn't be testing.

**Comment by abirbha** [comment]
Thank you for your answer ! 
This is exactly what i was afraid of ! 
So the order of attributes is undetectable using XMLUnit 1.6. ?
Is there another tool that provides attributes order detection ?

**Comment by bodewig** [comment]
What I was trying to say is that the order of attributes in simply not something that is defined. An XML parser is allowed to pass attributes to the application in a different order than it has been written inside of a string/file/whatever.

The only way a tool could provide the kind of comparison you want is by either not using an XML parser at all (but parse it itself) or use a fixed version of an XML parser that has deterministic behavior. JAXP, the standard XML parsing API of Java, does not provide any guarantees here.

From an XML specification point of view there is no difference between `<foo bar="1" baz=2"/>` and `<foo baz="2" bar="1"/>`.

I honestly don't know whether XMLUnit 1.6 can detect attribute order. It may be able to do so when you combine it with Apache Xerces 1.x as parser or Apache Crimson or any other ancient XML parser. It doesn't seem to be able to do so with current JDKs and their XML parsers. But the reason is the XML parser, not XMLUnit 1.6.

I'm not aware of any tool that would allow to reliable detect attribute order.
