### ISSUE TITLE
Complex XML comparison 

### ISSUE THREAD

**Issue by michailangelo** [xmlunit/xmlunit#173]
ControlXML:
> <Population>
	<Persons>
		<Person> 
			<PersonsId> 
				<Id>1
				</Id>
				<Age>35
				</Age> 
			</PersonsId> 
		</Person>
		<Person> 
			<OtherId> 
				<OtherInfo>FTW
				</OtherInfo> 
					<AnotherId>
						<Id>2
						</Id>
							<Nothing>Ok
							</Nothing>
				    </AnotherId>
			</OtherId>
		</Person>
	</Persons>
</Population>

TestXML:
> <Population>
	<Persons>
		<Person> 
			<OtherId> 
				<OtherInfo>FTW
				</OtherInfo> 
					<AnotherId>
						<Id>2
						</Id>
							<Nothing>Ok
							</Nothing>
				    </AnotherId>
			</OtherId>
		</Person>
		<Person> 
			<PersonsId> 
				<Id>1
				</Id>
				<Age>35
				</Age> 
			</PersonsId> 
		</Person>
	</Persons>
</Population>

I have the above XMLs  which I would like to compare ignoring the order on the Person node. I tried to use the `Diff  d = DiffBuilder.compare(Input.fromFile(expectedFile)).withTest(Input.fromFile(actualFile)).ignoreWhitespace()
                    .withNodeFilter(node -> !excludeNodes.contains(node.getNodeName()))
                    .checkForSimilar()
                    .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText, ElementSelectors.byName))
                    .build();`
but it doesnt work. It actually compares based on the order of Person node but I thought with the selector I used it will ignore the order. Should I use another selector or for these kind of situations I need to build custom DifferenceEvaluator?

**Comment by krystiankaluzny** [comment]
Hi @michailangelo 

Selecting elements by name and text doesn't work because Person nodes have only whitespaces as a text and because ElementSelectors.byNameAndText merge only text and cdata nodes and doesn't work recursively.
Solution is similar to https://github.com/xmlunit/xmlunit/issues/158, to a certain extent.

Matching nodes algorithm should look like this:

1. If current control node is 'Person' and test node is 'Person' 
   and control node contains 'PersionId' and test node contains 'PersioId' that have same data
   so current control and test nodes are match.
2. Else If current control node is 'Person' and test node is 'Person' 
   and control node contains 'OtherId' and test node contains 'OtherId' that have same data
   so current control and test nodes are match.
3. Otherwise (current control node is not 'Person') use default selector (match by name)

**DefaultNodeMatcher** works like _if, [if else, if else, ...], else_ for **ElementSelectors**, so yours **DiffBuilder** should be configured with

```java
.withNodeMatcher(new DefaultNodeMatcher(es1, es2, es3))
```

To create es1, es2 you can use ElementSelectors.conditionalBuilder()
```java
ElementSelector es1 = ElementSelectors.conditionalBuilder()
        .whenElementIsNamed("Person") // If current control node is 'Person' and test node is 'Person' 
        .thenUse(ElementSelectors.byXPath("./PersonsId", // and control node contains 'PersionId' and test node contains 'PersioId'
        				ElementSelectors.byName)) // that have same data
        .build();
```
```java
ElementSelector es2 = ElementSelectors.conditionalBuilder()
        .whenElementIsNamed("Person") // If current control node is 'Person' and test node is 'Person' 
        .thenUse(ElementSelectors.byXPath("./OtherId",  // and control node contains 'OtherId' and test node contains 'OtherId'
        				ElementSelectors.byName)) // that have same data
        .build();
```
As es3 you can use `ElementSelectors.byName`

I hope I helped

**Comment by michailangelo** [comment]
Indeed this helped indeed. Thanks a lot krystian!
