### ISSUE TITLE
Placeholder Handler for ISO 8601 dates

### ISSUE THREAD

**Issue by spalreddy** [xmlunit/xmlunit#174]
It would be useful to have placeholder handler for ISO 8601 date formats.

**Comment by spalreddy** [comment]
i am considering making a pull request on this using java.time.format.DateTimeFormatter which is introduced in Java 8, thus making this library work only from java 8 onwards. Would it be acceptable ?

**Comment by bodewig** [comment]
Sorry for the delay. The question isn't really that easy to answer :-)

I understand you want to use `java.time` over the mess that is `SimpleDateFormat` but bumping the Java requirement "just for that" feels a bit too much. OTOH it looks as if we'd start to alienate people who contribute by sticking with old APIs. Maybe we only change the requirements for the placeholders module? What do you think @krystiankaluzny ?

If we change the required version of Java we should make the next release 2.7.0 rather than a patch release.

**Comment by spalreddy** [comment]
Agree with you. Upgrading to Java 8 may need its own valid reasons than just this. Let me find sometime to make Pre Java 8 compatible pull request.

**Comment by bodewig** [comment]
I'll deal with this together with #178 and xmlunit/xmlunit.net/#31

**Comment by bodewig** [comment]
I've by now implemented a isDateTime placeholder, it is available in the 2.7.0-SNAPSHOT build I've published.
