### ISSUE TITLE
hasXPath does not work if the root element has xmlns /   xsi:schemaLocation

### ISSUE THREAD

**Issue by ablx** [xmlunit/xmlunit#175]
Using AssertJ and XML Unit, I get the following problem:

**Input**
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
   <version>foo</version>
</project>
```

**Assertions**
```
XmlAssert.assertThat(...).hasXPath("/project/version");
```

**Result**
```
java.lang.AssertionError: [XPath "/project/version" evaluated to node set] 
Expecting actual not to be empty

	at org.xmlunit.assertj.MultipleNodeAssert.exist(MultipleNodeAssert.java:74)
	at org.xmlunit.assertj.XmlAssert.hasXPath(XmlAssert.java:181)
```

**Expectation**
The assertion should work. If I use
```
<project>
   <version>foo</version>
</project>
```
everything works as expected.

**Versions**
```
org.xmlunit::xmlunit-assertj::2.6.3
```

**Comment by phbenisc** [comment]
Hi @ablx 

It's been a while since i used xmlunit-assertj, but did you set a namespace context?

Example (untested)

`    HashMap<String, String> prefix2Uri = new HashMap<String, String>();
    prefix2Uri.put("maven", "http://maven.apache.org/POM/4.0.0");
    assertThat(xml)
          .withNamespaceContext(prefix2Uri)
          .hasXPath("/maven:project/maven:version"));`

**Comment by ablx** [comment]
Thanks, this works.

**Comment by phbenisc** [comment]
Ah I add just a short explanation for future reference:
There is a difference between 
`<project xmlns="http://maven.apache.org/POM/4.0.0">` and  `<project>`.
The first one has explicitly a namespace assigned (for itself and for children). The second one has no namespace assigned.

xPath requires you to declare an namespace explicitly in order to identify the element. 

see [https://www.w3schools.com/xml/xml_namespaces.asp](w3schools - namespaces)
