### ISSUE TITLE
Node index updated when NodeFilter is used

### ISSUE THREAD

**Issue by monishaMaryMathew** [xmlunit/xmlunit#202]
We are currently using Xmlunit-core for Java version 2.6.3 in our Spring 4 app. This is working fine, even on using NodeFilter, the index is preserved to the original index as seen in the doc obj.

We recently migrated to SpringBoot, we have been using the same xmlunit-core 2.6.3 library. The Java code implementation for the comparison logic is the same. We are using a different JAXB plugin in the two project - this is the only difference. But, in this project the node index gets updated when we use the node filter feature in XmlUnit. 

Are we missing anything here, is there a specific dependency we should check? Please advise

**Comment by bodewig** [comment]
JAXB is only used if you are using `Input.fromJaxb` or `Input.from` with an object that is not one of the other that are supported specifically. I don't see how this would affect the indices (I assume you are asking because of #156 ).

My first guess would be that you only think you'd be using 2.6.3 but actually use an older version of XMLUnit.

**Comment by monishaMaryMathew** [comment]
There was a property tag overriding the version number to a lower one. Thanks a ton for pointing in the right direction. This helped resolve the issue.
