### ISSUE TITLE
Hacktoberfest participation

### ISSUE THREAD

**Issue by Boiarshinov** [xmlunit/xmlunit#230]
Hi!
What about participation in [Hacktoberfest initiative](https://hacktoberfest.digitalocean.com/)?
I think that it can be helpful for XmlUnit project.
As I know the only thing you should do to participate in Hacktoberfest is to add [this](https://github.com/topics/hacktoberfest) topic to project.

**Comment by bodewig** [comment]
As I cannot promise to be available to review PRs quick enough and thus would probably either get pressured in way I prefer not to be or disappoint people who are hoping for a shirt or a tree. This is why I have never participated in any of such initiatives.

While I really welcome each and every contribution I really do not want to be forced to review and merge a PR just because the end of a month is getting close.

**Comment by Boiarshinov** [comment]
Sorry to hear it. 
So then I'm closing the issue
