### ISSUE TITLE
ByNameAndTextRecSelector and element order

### ISSUE THREAD

**Issue by dhalbert** [xmlunit/xmlunit#77]
I'm trying to do matching where the element order of elements with different names may vary. In xmlunit 1 I used `RecursiveElementNameAndTextQualifier`, perhaps wrongly. In xmlunit 2, I thought the user guide is saying that `ByNameAndTextRecSelector` should work analogously, but I'm not successful. Here's a short test. Am I reading the user guide wrong, or perhaps it could use a clarification?

``` Java
import java.io.IOException;
import org.custommonkey.xmlunit.examples.RecursiveElementNameAndTextQualifier;
import org.xml.sax.SAXException;
import org.xmlunit.builder.DiffBuilder;
import org.xmlunit.builder.Input;
import org.xmlunit.diff.ByNameAndTextRecSelector;
import org.xmlunit.diff.DefaultNodeMatcher;

public class Test {

    public static void main(String[] args) throws SAXException, IOException {

        final String xml1 = "<root><a/><b/></root>";
        final String xml2 = "<root><b/><a/></root>";  // Flip <a/> and <b/>

        // xmlunit 1
        org.custommonkey.xmlunit.Diff diff1 = new org.custommonkey.xmlunit.Diff(xml1, xml2);
        diff1.overrideElementQualifier(new RecursiveElementNameAndTextQualifier());
        System.out.println("diff1.similar(): " + diff1.similar());

        // xmlunit 2
        org.xmlunit.diff.Diff diff2 = DiffBuilder
                .compare(Input.fromString(xml1))
                .withTest(Input.fromString(xml2))
                .checkForSimilar()
                .withNodeMatcher(new DefaultNodeMatcher(new ByNameAndTextRecSelector()))
                .build();
        System.out.println("diff2.hasDifferences(): " + diff2.hasDifferences());
        diff2.getDifferences().forEach(difference -> System.out.println(difference));
    }
}
```

**Comment by bodewig** [comment]
If this is a real example then yes, you never needed to use `RecursiveElementNameAndTextQualifier` - there is no nested text at all and recursion isn't necessary either. :-)

In XMLUnit 1.x `ElementNameQualifier` (which is the default) should do, for XMLUnit 2.x it would be `ElementSelectors.byName`.

**Comment by bodewig** [comment]
I've run your test, the problem is with the `root` element rather than the nested elements. `ByNameAndTextRecSelector` doesn't want you to compare the respective `root` elements.

`ByNameAndTextRec` enforces the same order on the nested elements of elements it compares. This seems to be a regression and I'm torn between calling it a regression or an undocumented feature :-)

If we keep it that way people will be kept away from abusing it the way `RecursiveElementNameAndTextQualifier` has been used - or at least restrict it to the elements where it is needed.

**Comment by dhalbert** [comment]
Thanks for your comments. The real use case is that I have a XML structure in which I don't care about the order of the elements or attributes at any level, but the tag names, attributes, and text should all match. This would be sort of like comparing JSON with only  { }, no [ ] sequences. For example:

```
<root>
  <a attr1="foo" attr2="bar">
    <a1>A1</a1>
    <a2>A2</a2>
    <a3>A3</a3>
  </a>
  <b>
    <b1>B1</b1>
    <b2>B2</b1>
  </b>
</root>
```

should match:

```
<root>
  <b>
    <b2>B2</b1>
    <b1>B1</b1>
  </b>
  <a attr2="bar" attr1="foo">
    <a2>A2</a1>
    <a3>A3</a3>
    <a1>A1</aa>
  </a>
</root>
```

**Comment by bodewig** [comment]
Sounds like `and(byNameAndText, byNameAndAllAttributes` - untested.

**Comment by dhalbert** [comment]
I tried
```
.withNodeMatcher(
  new DefaultNodeMatcher(ElementSelectors.and(
    ElementSelectors.byNameAndText,
    ElementSelectors.byNameAndAllAttributes)))
```
and it worked, with the more complicated example I gave above. Interestingly, I also tried just
```
.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
```
Surprisingly to me, that also worked. I thought it would ignore attributes, but it reported differences when I changed an attribute or dropped an attribute value. So I'm not sure why that worked as well for attribute matching.

Also, I tried the xmlunit 1 case with `RecursiveElementNameAndTextQualifier`, and that did _not_ report a match with the more complicated example above. Now I'm confused as to why I thought it would.

The way I'm thinking about specifying these matches is that I want a particular element's subelements to match either as a sequence (order matters) or as a multiset (order doesn't matter). In the case above I want it to be multiset and recursive. I'm trying to express a schema specification programmatically (at least partially), but that can get pretty tricky.

Anyway, thanks for your help. Perhaps this points towards some more examples that could be added to the user guide.

**Comment by bodewig** [comment]
Feel free to add examples - it is somewhat hard to come up with them out of nothing. You should be able to change the Wiki.

Shortly after I gave the `and` answer I thought it might have become to specific.

There are two comparisons happening in at the same time: `NodeMatcher` decides which nodes to compare with each other at all - by letting `ElementSelector` compare them in case of elements. And then there is the comparison of the difference engine.

You can encode your comparisons in the `ElementSelector` like I translated the requirement "tag names, attributes, and text should all match" into `and(byNameAndText, byNameAndAllAttributes)` so it will only ever pick a pair of elements to compare if everything matches as expected. But this also means if a nested text or an attribute is different - you won't get to see a `Difference` for the text or attribute at all. You get two `CHILD_LOOKUP` differences because `NodeMatcher` didn't find partners for the control and test nodes.

OTOH if you make the `ElementSelector` loose enough that it will never pick the wrong pair when faced with an unordered set of elements, you get more detailed comparison outcomes.

In your example document the element name alone would have been enough to select the correct pairs. `byNameAndText` alone is a bit more specific and the `and` construct is the most specific.

I guess my advice would be to pick the loosest possible `ElementSelector` so you get the most details if there are differences that shouldn't be there.

**Comment by bodewig** [comment]
Does https://github.com/xmlunit/user-guide/wiki/SelectingNodes#advice-on-picking-the-best-elementselector make sense?

**Comment by dhalbert** [comment]
Thanks for addition to `SelectingNodes`. This is a helpful level of additional detail. However, for me I was really enlightened by your earlier comment:

> There are two comparisons happening in at the same time: NodeMatcher decides which nodes to compare with each other at all - by letting ElementSelector compare them in case of elements. And then there is the comparison of the difference engine.

This was the "Aha!" moment for me. I re-read the user guide and I now see that the "two comparisons" is implied by a lot of the text there, but not said explicitly early on (I think). The difference engine has default matching rules (https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator#default-differenceevaluator) but NodeMatcher/ElementSelector filters what gets handed to the difference engine. So you can tune what the difference engine sees.

I now understand much better what is going on. I could try to add a paraphrase of the quote above to the user guide, but perhaps you might do a better job. After I get my code working, I can try to add some more examples with explanation to the guide.

**Comment by bodewig** [comment]
This is valuable feedback, thanks, I'll give it a shot sometime later.

Looking forward to more examples. :-)

**Comment by bodewig** [comment]
wow, it took me a year to update the user guide. Embarrassing. But finally done.

**Comment by KiranBolaj** [comment]
Hi,
Is there any way to compare the two XML files by partially comparing the value of that particular element by specifying the delimiter of that string value of that particular node element?

**Comment by bodewig** [comment]
@KiranBolaj many thanks for opening #113 this is a lot better than hijacking unrelated issues.
