### ISSUE TITLE
How to ignore Doctype-Declarations

### ISSUE THREAD

**Issue by dieterbaier** [xmlunit/xmlunit#82]
#I use the DiffBuilder to compare two XML-Sources. The Sources do have a Doctype-Declaration at the beginning.

Is there any possibility to tell the DiffBuilder not to ignore any Schema-References, nor it should not validate any XMLs?

Thanks

Dieter

P.S.: using XMLUnit 2.1.1

**Comment by bodewig** [comment]
Hi Dieter,

I had seen https://github.com/xmlunit/user-guide/issues/4 - I've just not been quick enough ;-)

If I understand correctly, you need to tell the parser to not validate the documents, am I correct?

In order to do that you'd need to set the `DocumentBuilder` or `DocumentBuildFactory` to not validate the document. Unfortunately `DOMDifferenceEngine` doesn't allow you to select the factory, it directly uses the single-arg version of `Convert.toNode`. We could add an optional field for setting the `DocumentBuildFactory` to `DOMDifferenceEngine` - and from there in `DiffBuilder` and `CompareMatcher`. This could be an enhancement for the next release.

As a workaround you should be able to create the `Node` or `Document` instances yourself. Rather than

```java
DiffBuilder.compare(STRING_HOLDING_XML)
    .withTest(ANOTHER_STRING_HOLDING_XML)
    ...
```

you can use

```java
DocumentBuilderFactory dbf = ... set up a factory that is not validating ...
Document control = Convert.toDocument(Input.fromString(STRING_HOLDING_XML).build(), dbf);
Document test = Convert.toDocument(Input.fromString(ANOTHER_STRING_HOLDING_XML).build(), dbf);
DiffBuilder.compare(control)
    .withTest(test)
    ...
```

Does this work for you?

**Comment by dieterbaier** [comment]
Hi Stefan,

thank's for the quick response. Your workaround did help.

For some reason, I didn't get to see the possibility of giving a document to the DiffBuilder.

A convinience-method on the builder for giving the DocumentBuilderFactory to the builder would be great.

Best regards

Dieter

**Comment by bodewig** [comment]
I'm glad it worked. I've created #83 as a follow-up enhancement request.
