### ISSUE TITLE
Problem with choosing the proper node matcher for xml with different order of elements.

### ISSUE THREAD

**Issue by deckertm** [xmlunit/xmlunit#95]
Hi,

I'm new to XMLUnit. Currently I'm trying to make a comparison of two xml documents. Their structure is similar to xml1:
```
<root>
<test>
<node>
<child1>test1</child1>
<child2>test2</child2>
</node>
<node>
<child1>test3</child1>
<child2>test4</child2>
</node>
</test>
</root>
```
and xml2:
```
<root>
<test>
<node>
<child2>test4</child2>
<child1>test3</child1>
</node>
<node>
<child2>test2</child2>
<child1>test1</child1>
</node>
</test>
</root>
```
As you can see the content is the same however the order of 'nodes' and their children differs. Currently I'm using .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.conditionalBuilder().whenElementIsNamed("test").thenUse(new ByNameAndTextRecSelector()).elseUse(ElementSelectors.byName). With this node matcher I got information about comparison with NULL. I'd like to get no differences. Can you suggest a better way how to compare this kind of content? Thank you in advance for your help!

Kind regards,
deckertm

**Comment by bodewig** [comment]
Don't use `ByNameAndTextRecSelector` it is almost never the correct solution. Even if it works it does so by accident most of the time.

```java
DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("test").thenUse(ElementSelectors.byXpath("./node/child1", ElementSelectors.byNameAndText)
    .elseUse(ElementSelectors.byName)
```

looks as if it should work. I haven't tried, though.

For the full story, please see https://github.com/xmlunit/user-guide/wiki/SelectingNodes

**Comment by deckertm** [comment]
I've tested your proposal, however this did not work for me. :( I still get differences between child1 nodes. Moreover, how to compare the other child nodes? I've tried combining xpath selectors for each child nodes with 'or'. This also did not work. :( Any other hints? Kind regards.

**Comment by bodewig** [comment]
I see I read your example wrong. Your `test` nodes have more than one `node`, I thought it had been different `test`s.

You need to tackle it from the root element asking yourself a few questions for each element. Most importantly

* is there more than one element of the given name - if note `byName` will be enough. Otherwise you need a more complex logic.
* what is it that identifies the "correct" nodes to match. Create an `ElementSelector` that is sensitive to just that.

In your case I only see a single `test` node, so we can safely ignore it.

There are multiple `node` children. When you look at them, what is it that provides an identity to the `node`? Is it the text nested into the `child1` element? Then

```java
DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("node").thenUse(ElementSelectors.byXpath("./child1", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byName)
```

should properly select it.

If there is more than one `test` in a real example, how do you identify the "correct" test yourself?

There is no generic recipe, only a toolbelt of selectors that you need to combine in order to find the best `ElementSelector` to your domain of XML document.

**Comment by deckertm** [comment]
Thank you for your tips. :) Now it's working properly. Btw. great tool! It's really helpful!

**Comment by bodewig** [comment]
Thanks
